{
 "title": "Users Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Live traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  current_traffic AS metric,\n  current_traffic AS \"current_traffic\"\nFROM traffic\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Current Logins",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  current_traffic AS metric\nFROM traffic\nORDER BY time"
    }
   ]
  },
  {
   "title": "Portals Traffic",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Ultimatix as Home,\n  Knome as Careers,\n  TCSION as Exam_Portal,\n  TCSXplore as Learning_Portal\nFROM active"
    }
   ]
  },
  {
   "title": "Scores Ranges",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  scores As metric\nFROM users"
    }
   ]
  },
  {
   "title": "Courses Popularity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  course_name as metric,\n  views as value\nFROM courses"
    }
   ]
  },
  {
   "title": "Learning Platform Popularity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() as time,\n  websites as metric,\n  visitors as value\nFROM learn"
    }
   ]
  },
  {
   "title": "Gender Analysis",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  sum( case when gender = 'Male'\r\n                 then 1 else 0 end )    as Male\r\n     , sum( case when gender = 'Female'\r\n                 then 1 else 0 end )    as Female\r\n  from user_details\r\n"
    }
   ]
  },
  {
   "title": "Average Score Panel",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(marks) as metric\nFROM user_details"
    }
   ]
  }
 ]
}